baseURL = "https://www.sgfoot.com/"
languageCode = "zh-CN"
title = "百里江山的博客"
theme = "maupassant"
googleAnalytics = "UA-163385108-1"  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140
uglyURLs = false # 添加html后缀

# disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "百里江山"

[params]
  author = "百里江山"
  subtitle = "专注于Go语言(golang)、软件架构、前沿技术"
  keywords = "Go语言,Golang开发,算法,设计模式,架构,Linux,Kubernetes,Docker"
  description = "Go语言,Golang开发,算法,设计模式,架构,Linux,Kubernetes,Docker-百里江山的个人博客"
  busuanzi = true #启用不算子网页统计
  googleAd = "ca-pub-6145899430951391"  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = []
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

#[[params.links]]
 # title = "飞雪无情的博客"
  #name = "飞雪无情的博客"
  #url = "https://www.flysnow.org/"

## 侧边栏广告位
#[[params.ads]]
  #title = "【2019双12】ALL IN CLoud 低至1折"
  #url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
  #img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "yezihack/yezihack.github.io" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 优化url
[permalinks]
	post = "/:year/:month/:day/:filename"
	#post = "/:year/:month/:day/:slug"
## 配置网站菜单
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/archives"
[[menu.main]]
  name = "标签云"
  weight = 30
  identifier = "tags"
  url = "/tags.html"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories.html"
[[menu.main]]
  name = "每日算法"
  weight = 40
  identifier = "algo"
  url = "/tags/每日算法.html"
